### PR TITLE
Notifications theme v2

### LINKED ISSUE #277: Apply theme-v2 for notification component
- [ ] Layout
- [ ] Theme
- [ ] RTL support
- [ ] Component layer variable docs

### PR DESCRIPTION
**Pull request by szuperaz**
closes #277 

## Figma
Screenshot 2022-06-20 at 14 09 54
Screenshot 2022-06-20 at 14 11 59
Screenshot 2022-06-20 at 16 49 20

## Implementation

For the notification positioning, we should take into account the edit message modal, notifications should also be visible when this modal is open - I ended up positioning the notifications at the middle-bottom of the screen so they look ok with the modal open as well - will also discuss this with Fra after he is back in the office

Screenshot 2022-06-20 at 14 04 21
Screenshot 2022-06-20 at 14 04 12
Screenshot 2022-06-20 at 14 20 34
Screenshot 2022-06-20 at 14 18 14

### CODE REVIEW

**Comment by petyosi** [comment]
I'm a bit concerned about the notification being on top of the message input. Also, thinking from the integrator's perspective, I would rather have the notification relative to the "main" chat UI (so that it clearly relates to the state of the chat vs the entire app).

Ultimately, I think this should be something that we expose as a React hook/Angular service (probably we do it already) and let the integrators wire it up to their app notification system. However, if we have to keep it, I would rather move it to the center top of the message list. @NiftyGift - please let us know what you think, we can have a call if necessary.

**Comment by szuperaz** [comment]
> I'm a bit concerned about the notification being on top of the message input. Also, thinking from the integrator's perspective, I would rather have the notification relative to the "main" chat UI (so that it clearly relates to the state of the chat vs the entire app).
> 
> Ultimately, I think this should be something that we expose as a React hook/Angular service (probably we do it already) and let the integrators wire it up to their app notification system. However, if we have to keep it, I would rather move it to the center top of the message list. @NiftyGift - please let us know what you think, we can have a call if necessary.

I think it's good to keep it for demo apps, in Angular we have a service to receive the notifications, and integrators can just omit the `stream-notification-list` element from the chat UI if they don't need it - so yes, it's easy to replace.

"I would rather have the notification relative to the "main" chat UI" - do you mean relative to the message list, or do you mean shouldn't position it relative to the viewport?

**Comment by petyosi** [comment]
I mean relative to the message list.

**Comment by szuperaz** [comment]
I did a few different layouts with the help of @NiftyGift , but I ended up reverting to the old layout, on the way I realized the followings:
- Our SDK is built in a way that we rely on notifications a lot
  - for example if a file upload is unsuccessful we display a notification (we could have the error message near the file UI element)
  -  another one: we don't have an error screen for channel/channel list -> if we can't init the chat app we need a notification
-> this makes it necessary for us to display notifications inside SDK components
- The message edit in the modal window also makes notifications much more complex -> we want to move away from that
- The NotificationService should add an action label to the notifications so integrators can decide what kind of notifications they want to display
- We could have built-in hooks inside SDK components where integrators can inject notifications (Fra did a lot of research, and for example, the top of the channel list is a typical place for notifications, also top/bottom of messsage list etc.)

Screenshot 2022-06-22 at 10 44 19
Screenshot 2022-06-22 at 10 44 26
Screenshot 2022-06-22 at 10 56 12

Please note: if an error happens when only the thread is visible (mobile layout) notifications won't be displayed -> this is a problem with theme-v1 as well

**Review by petyosi — APPROVED** [review]

**Pull request merged**
