### PR TITLE
feat: Implement user mentions #143

### LINKED ISSUE #143: Mention users
- Implement it in an opt-in manner
- Autocompletion should be triggered by '@' character
- Local search in channel participants
- Template for autocomplete list item should be customizable

#127, #126

- [x] Expose listItem template for customization
- [x] Expose input to turn off mentions
- [x] Implement autocomplete for channel members (key: name, fallback for id)
- [x] Mentioned users should be added to the `mentioned_users` array
- [x] Hightlight mentioned users in the message
- [x] Update docs (write about opt-in architecture) and tutorial

### LINKED ISSUE #144: Add possibility to search for all app users in mentions
Add parameter that decides if we should do a local search (channel members) or backend search with all app users included for mentions

### PR DESCRIPTION
**Pull request by szuperaz**
BREAKING CHANGE: Besides `StreamChatModule` you also need to import `StreamAutocompleteTextareaModule` or `StreamTextareaModule`

closes #143 
closes #144

### CODE REVIEW

**Comment by szuperaz** [comment]
@petyosi it feels strange to jump to v2.0.0 already, but we have a breaking that we can't work around

**Review by petyosi — APPROVED** [review]
This looks good to me. There are a few additional items that we need to develop, but they better be a separate PRs:
- Support configuration for handling the click of the mentioned user (integrators use it to navigate to the user profile).
- Support configuration for handling the hover of the mentioned user (usually, some popup with user info).
- Support configuration for mentioning all app users (VS the ones that are in the channel). 

If you need any further clarification of the above, let me know.

**Comment by szuperaz** [comment]
> 

GH issue for the first two: https://github.com/GetStream/stream-chat-angular/issues/149

All app user search is added to the PR

**Review by petyosi — APPROVED** [review]

**Pull request merged**
